/* Wise Acres: the footer art, for the pages that have no hero picture.
 * GENERATED by tools/pages.py from js/hero.js (the same code, only the parts the footer needs). Do not edit this file: edit js/hero.js and run
 *   python3 tools/pages.py
 * The home page loads js/hero.js instead. */
(() => {
  'use strict';

  const W = window.WISE_ACRES;

  if (!W || !W.seasons) return;

  const doc = document;

  const $ = (s, c = doc) => c.querySelector(s);

  const $$ = (s, c = doc) => Array.from(c.querySelectorAll(s));

  const rand = W.rand;

  const INK = '#3a2416';

  /* ------------------------------------------------------------------ *
   * Drawing helpers
   * ------------------------------------------------------------------ */
  const f1 = (n) => Math.round(n * 10) / 10;

  const use = (id, x, y, w, h, extra = '') => `<use href="#${id}" x="${f1(x)}" y="${f1(y)}" width="${f1(w)}" height="${f1(h)}" ${extra}/>`;

  // Grass / snow-drift edge along the bottom. Overflowing the viewBox avoids seams while parallax scrolls.
  const blades = (base, minH, maxH, step, fill, seed) => {
    const r = rand(seed);
    let d = `M-40 700V${base}`;
    for (let x = -40; x <= 1480; x += step) d += `L${x + step / 2} ${(base - minH - r() * (maxH - minH)).toFixed(0)}L${x + step} ${base}`;
    return `<path d="${d}V700Z" fill="${fill}" stroke="${INK}" stroke-width="3" stroke-linejoin="round"/>`;
  };

  const sunflower = (x, y, w, cls) =>
    `<g><g class="sway ${cls}"><use href="#sunflower-plant" x="${x}" y="${y}" width="${w}" height="${f1(w * 380 / 140)}"/></g></g>`;

  /* A pickable thing: a group that is clickable, animates when picked and regrows. */
  const pickable = (x, y, inner, hit, origin = '50% 0', kind = 'fruit', cls = '') =>
    `<g class="berry-hit${cls ? ' ' + cls : ''}" transform="translate(${f1(x)} ${f1(y)})" data-pick="${kind}"><g class="berry" style="--o:${origin}">${inner}</g>` +
    `<rect x="${f1(hit.x)}" y="${f1(hit.y)}" width="${f1(hit.w)}" height="${f1(hit.h)}" fill="transparent"/></g>`;

  /* ------------------------------------------------------------------ *
   * SUMMER — blueberry bushes
   * ------------------------------------------------------------------ */
  const blueBerry = (r, ripe = true) =>
    `<circle r="${f1(r)}" fill="${ripe ? '#4d5fc9' : '#a8b4ea'}" stroke="${INK}" stroke-width="2"/>` +
    `<path d="M0 ${f1(-r * 0.46)}l${f1(r * 0.3)} ${f1(r * 0.24)}-${f1(r * 0.12)} ${f1(r * 0.36)}h-${f1(r * 0.36)}l-${f1(r * 0.12)}-${f1(r * 0.36)}Z" transform="translate(${f1(r * 0.12)} ${f1(r * 0.18)})" fill="${ripe ? '#2c3a86' : '#7d8acb'}"/>` +
    `<ellipse cx="${f1(-r * 0.38)}" cy="${f1(-r * 0.4)}" rx="${f1(r * 0.24)}" ry="${f1(r * 0.34)}" fill="#fff" opacity=".5" transform="rotate(30 ${f1(-r * 0.38)} ${f1(-r * 0.4)})"/>`;

  // local bush coordinates: 100 x 80, base centre (50, 80)
  const BUSH_RIPE = [[22, 54], [36, 44], [52, 36], [66, 42], [79, 52], [45, 60], [62, 60], [30, 68], [72, 68]];

  const BUSH_GREEN = [[14, 62], [86, 60], [54, 70]];

  function bush(cx, cy, w, pickN) {
    const s = w / 100, h = 80 * s, ox = cx - w / 2, oy = cy - h;
    const sw = f1(2.8 / s);
    let out = `<g transform="translate(${f1(ox)} ${f1(oy)}) scale(${f1(s * 1000) / 1000})">` +
      `<ellipse cx="50" cy="80" rx="52" ry="7" fill="rgba(58,36,22,.2)"/>` +
      `<path d="M6 80C-2 60 6 40 22 38C20 20 44 6 58 18C72 4 96 20 92 38C106 46 102 70 94 80Z" fill="#2e7d3a" stroke="${INK}" stroke-width="${sw}" stroke-linejoin="round"/>` +
      `<g fill="#43a047"><ellipse cx="30" cy="48" rx="15" ry="8" transform="rotate(-24 30 48)"/><ellipse cx="66" cy="34" rx="16" ry="8" transform="rotate(18 66 34)"/><ellipse cx="50" cy="62" rx="17" ry="8" transform="rotate(-6 50 62)"/><ellipse cx="82" cy="58" rx="11" ry="7" transform="rotate(26 82 58)"/></g>` +
      `<g fill="#66bb6a"><ellipse cx="34" cy="42" rx="8" ry="4" transform="rotate(-24 34 42)"/><ellipse cx="62" cy="30" rx="8" ry="4" transform="rotate(18 62 30)"/></g>` +
      `<g fill="none" stroke="#1f5f2b" stroke-width="1.3" stroke-linecap="round" opacity=".55"><path d="M17 51l26-6M52 62l28-6M56 34l22 6M72 55l22 4M26 44l16-2M44 30l12 2"/><path d="M20 46c2 4 5 6 9 6M70 60c3 3 7 4 11 3M60 38c2 3 6 4 9 3"/></g>` +
      `<g fill="#86c98a" opacity=".7"><ellipse cx="22" cy="40" rx="6" ry="3" transform="rotate(-30 22 40)"/><ellipse cx="76" cy="44" rx="6" ry="3" transform="rotate(25 76 44)"/><ellipse cx="42" cy="22" rx="6" ry="3" transform="rotate(-10 42 22)"/></g>` +
      `<path d="M14 66c14 5 30 6 44 4" fill="none" stroke="#1f5f2b" stroke-width="2.2" stroke-linecap="round" opacity=".5"/>`;
    BUSH_GREEN.forEach(([x, y]) => { out += `<g transform="translate(${x} ${y})">${blueBerry(4.2, false)}</g>`; });
    if (pickN === 0) BUSH_RIPE.slice(0, 5).forEach(([x, y]) => { out += `<g transform="translate(${x} ${y})">${blueBerry(5.6)}</g>`; });
    out += '</g>';
    // pickable ripe berries live in global coordinates so their hit areas stay a sensible size
    if (pickN > 0) {
      BUSH_RIPE.slice(0, pickN).forEach(([bx, by]) => {
        const r = 5.6 * s, hit = r + 5;
        out += pickable(ox + bx * s, oy + by * s, blueBerry(r), { x: -hit, y: -hit, w: hit * 2, h: hit * 2 }, '50% 50%');
      });
    }
    return out;
  }

  /* ------------------------------------------------------------------ *
   * FALL — pumpkin patch, road with a tractor + wagon, scarecrow
   * ------------------------------------------------------------------ */
  const leafUse = (x, y, a, s, fill = '#4aa04a') =>
    `<use href="#pumpkin-leaf" transform="translate(${f1(x)} ${f1(y)}) rotate(${a}) scale(${s})" fill="${fill}" stroke="${INK}" stroke-width="${f1(2.4 / s)}" stroke-linejoin="round"/>`;

  const bale = (x, y, w, h) =>
    `<g stroke="${INK}" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="7" fill="#f0c95a"/>` +
    `<path d="M${x + 8} ${f1(y + h * 0.3)}h${w - 16}M${x + 8} ${f1(y + h * 0.62)}h${w - 16}" stroke="#c19a2c" stroke-width="2" fill="none"/>` +
    `<path d="M${f1(x + w * 0.3)} ${y}v${h}M${f1(x + w * 0.7)} ${y}v${h}" stroke="#8f6f16" stroke-width="3" fill="none"/>` +
    `<path d="M${x + 4} ${y + 4}l6 -6M${x + w - 12} ${y - 1}l6 -6M${f1(x + w * 0.5)} ${y}l3 -7" stroke="#e9c35b" stroke-width="3" fill="none"/></g>`;

  function corn(x, base, h) {
    const s = h / 300;
    const leaf = (y, dir, len) => `<path d="M0 ${y}C${dir * 30} ${y - 16} ${dir * len} ${y - 4} ${dir * (len + 14)} ${y + 46}C${dir * (len - 12)} ${y + 30} ${dir * 22} ${y + 14} 0 ${y}Z" fill="#a9c03c" stroke="${INK}" stroke-width="3" stroke-linejoin="round"/>`;
    return `<g transform="translate(${x} ${base}) scale(${f1(s * 100) / 100})"><g class="sway ${x % 2 ? 's2' : 's3'}">` +
      `<path d="M0 0V-300" stroke="${INK}" stroke-width="13" stroke-linecap="round"/><path d="M0 0V-300" stroke="#8fb03a" stroke-width="7" stroke-linecap="round"/>` +
      leaf(-60, -1, 80) + leaf(-105, 1, 86) + leaf(-150, -1, 78) + leaf(-195, 1, 72) + leaf(-240, -1, 60) +
      `<path d="M4 -150C30 -164 38 -122 24 -102C15 -96 5 -110 4 -150Z" fill="#7cae3a" stroke="${INK}" stroke-width="3" stroke-linejoin="round"/>` +
      `<path d="M10 -146C22 -150 30 -128 22 -108M16 -142C24 -136 28 -124 24 -110" fill="none" stroke="#4f8a2a" stroke-width="2" opacity=".7"/>` +
      `<path d="M14 -120C22 -126 30 -118 22 -104Z" fill="#ffcf3d"/><path d="M16 -118l5 -3M17 -112l6 -3M18 -106l4 -2" stroke="#d99a00" stroke-width="1.6" stroke-linecap="round" fill="none"/>` +
      `<path d="M-2 -230C-20 -244 -22 -206 -12 -190C-6 -188 0 -200 -2 -230Z" fill="#7cae3a" stroke="${INK}" stroke-width="3" stroke-linejoin="round"/><path d="M-12 -200l-6 -4M-8 -196l-7 -2" stroke="#d99a00" stroke-width="2" stroke-linecap="round"/>` +
      `<path d="M0 -300l-8-26M0 -300l4-30M0 -300l14-24" stroke="#d9b45a" stroke-width="4" stroke-linecap="round" fill="none"/></g></g>`;
  }

  function snowman(x, y) {
    const sk = `stroke="${INK}" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"`;
    return `<g class="npc" data-npc="snowman" transform="translate(${x} ${y}) scale(.95)"><g class="sway s3">` +
      `<ellipse cx="0" cy="2" rx="58" ry="9" fill="rgba(58,36,22,.18)"/>` +
      `<path d="M-31 -102L-80 -130M-58 -116L-62 -138M-68 -122L-92 -122" stroke="${INK}" stroke-width="9" stroke-linecap="round" fill="none"/><path d="M-31 -102L-80 -130M-58 -116L-62 -138M-68 -122L-92 -122" stroke="#8a5a35" stroke-width="4.6" stroke-linecap="round" fill="none"/>` +
      `<path d="M31 -102L80 -122M58 -112L64 -132M70 -117L92 -112" stroke="${INK}" stroke-width="9" stroke-linecap="round" fill="none"/><path d="M31 -102L80 -122M58 -112L64 -132M70 -117L92 -112" stroke="#8a5a35" stroke-width="4.6" stroke-linecap="round" fill="none"/>` +
      `<circle cx="0" cy="-46" r="48" fill="#fff" ${sk}/><path d="M-30 -20a48 48 0 0 0 44 24" fill="none" stroke="#cfe0f0" stroke-width="6" stroke-linecap="round"/>` +
      `<circle cx="0" cy="-108" r="35" fill="#fff" ${sk}/><path d="M-22 -88a35 35 0 0 0 34 14" fill="none" stroke="#cfe0f0" stroke-width="5" stroke-linecap="round"/>` +
      `<circle cx="0" cy="-160" r="26" fill="#fff" ${sk}/>` +
      `<circle cx="0" cy="-92" r="4.4" fill="${INK}"/><circle cx="0" cy="-108" r="4.4" fill="${INK}"/><circle cx="0" cy="-58" r="4.6" fill="${INK}"/><circle cx="0" cy="-42" r="4.6" fill="${INK}"/><circle cx="0" cy="-26" r="4.6" fill="${INK}"/>` +
      `<circle cx="-9" cy="-166" r="3.6" fill="${INK}"/><circle cx="9" cy="-166" r="3.6" fill="${INK}"/><circle cx="-8" cy="-167" r="1.1" fill="#fff"/><circle cx="10" cy="-167" r="1.1" fill="#fff"/>` +
      `<path d="M0 -161l28 5-28 6Z" fill="#f57c1f" ${sk}/>` +
      `<path d="M-13 -150q3 4 7 5M-4 -147q4 2 8 1M5 -148q3 1 8-1M12 -152q2 2 4 2" fill="none" stroke="${INK}" stroke-width="2.4" stroke-linecap="round"/>` +
      `<path d="M-28 -136q28 12 56 0v12q-28 12 -56 0Z" fill="#e5334b" ${sk}/><path d="M12 -128l6 30q3 8 12 6l-4-30Z" fill="#e5334b" ${sk}/><path d="M-14 -134v10M0 -132v11M14 -134v10" stroke="#fff" stroke-width="3" stroke-linecap="round" opacity=".7"/>` +
      `<path d="M16 -102l3 14M24 -100l2 12" stroke="${INK}" stroke-width="2" stroke-linecap="round" opacity=".45" fill="none"/>` +
      `<g fill="#cfe0f0" opacity=".9"><circle cx="-26" cy="-70" r="2.4"/><circle cx="-34" cy="-40" r="2"/><circle cx="26" cy="-30" r="2.4"/><circle cx="20" cy="-72" r="2"/></g>` +
      `<g fill="#fff" stroke="none" opacity=".95"><path d="M-72 -150l2 4 4 1-4 1-2 4-2-4-4-1 4-1Z"/><path d="M70 -166l2 4 4 1-4 1-2 4-2-4-4-1 4-1Z"/></g>` +
      `<circle cx="-1.4" cy="-93.4" r="1.2" fill="#fff" opacity=".6"/><circle cx="-1.4" cy="-59.4" r="1.2" fill="#fff" opacity=".6"/>` +
      `<g class="sn-hat"><rect x="-27" y="-186" width="54" height="10" rx="3" fill="#2b2b33" ${sk}/><rect x="-17" y="-214" width="34" height="30" rx="3" fill="#2b2b33" ${sk}/><rect x="-17" y="-192" width="34" height="8" fill="#43a047" stroke="${INK}" stroke-width="2.4"/>` +
      `<rect x="-4" y="-191" width="8" height="6" rx="1.4" fill="#ffc928" stroke="${INK}" stroke-width="1.6"/><path d="M-12 -208h6" stroke="#fff" stroke-width="2.6" stroke-linecap="round" opacity=".35"/></g>` +
      `</g><rect class="npc-hit" x="-62" y="-232" width="124" height="238" fill="transparent"/></g>`;
  }

  /* ------------------------------------------------------------------ *
   * Footer: a row of the season's crops standing on the dark soil of the footer
   * ------------------------------------------------------------------ */
  const footerEl = $('#footer-field');

  function footerArt(id) {
    const r = rand(77 + id.length), W_ = 1440, BASE = 130;
    let out = '';
    if (id === 'fall') {
      const kinds = ['pumpkin', 'pumpkin', 'pumpkin-b', 'pumpkin-w'];
      out += corn(44, 142, 150) + corn(84, 146, 118) + corn(1372, 142, 146) + corn(1400, 146, 112);
      for (let x = 130; x < 1300; x += 48 + r() * 62) {
        const w = 32 + r() * 36, h = w * 92 / 110;
        out += leafUse(x + w * 0.1, BASE - 8, -50, w / 120, '#4aa04a') + use(kinds[Math.floor(r() * 4)], x, BASE - h - 2, w, h);
      }
      out += bale(650, BASE - 40, 76, 40) + blades(BASE, 5, 13, 20, '#dcb85c', 5);
    } else if (id === 'winter') {
      for (let x = 20; x < W_; x += 40 + r() * 54) {
        const h = 62 + r() * 54, w = h * 0.727;
        out += use('fir', x, BASE - h - 6, w, h) + use('fir-snow', x, BASE - h - 6, w, h);
      }
      out += `<g transform="translate(1040 ${BASE + 6}) scale(.3)">${snowman(0, 0)}</g>` +
        `<path d="M-20 ${BASE + 20}V${BASE - 6}C120 ${BASE - 14} 260 ${BASE - 2} 420 ${BASE - 8}S720 ${BASE - 16} 900 ${BASE - 6} 1200 ${BASE - 14} 1460 ${BASE - 6}V${BASE + 20}Z" fill="#fff" stroke="${INK}" stroke-width="3" stroke-linejoin="round"/>`;
    } else if (id === 'spring') {
      for (let x = 40; x < W_; x += 78 + r() * 26) {
        const w = 58 + r() * 18, h = w * 0.75;
        out += use('sb-plant', x - w / 2, BASE - h * 0.94 - 4, w, h) + use('strawberry', x - w * 0.36, BASE - h * 0.62, w * 0.24, w * 0.27) + use('strawberry', x + w * 0.16, BASE - h * 0.5, w * 0.2, w * 0.225);
      }
      out += sunflower(18, BASE - 118, 42, '') + sunflower(1378, BASE - 126, 44, 's2') + blades(BASE, 5, 13, 20, '#5cb85c', 15);
    } else {
      for (let x = 60; x < W_; x += 96 + r() * 34) out += bush(x, BASE + 2, 76 + r() * 26, 0);
      out += sunflower(14, BASE - 122, 44, '') + sunflower(74, BASE - 96, 34, 's2') + sunflower(1352, BASE - 124, 44, 's3') + sunflower(1402, BASE - 96, 34, '') + blades(BASE, 5, 13, 20, '#5cb85c', 19);
    }
    return `<svg viewBox="0 0 ${W_} ${BASE}" preserveAspectRatio="xMidYMax slice" focusable="false">${out}</svg>`;
  }

  /* ------------------------------------------------------------------ *
   * Build a season
   * ------------------------------------------------------------------ */
  // data-only="fall winter": shown only while one of those seasons is on screen. Add data-in-season to show it only
  // while that season is really happening (not in the weeks before or after, when the nearest season is shown).
  // data-out-of-season="spring" is the opposite: hidden while that season is really happening ("Tell me when it opens").
  function applyOnly(id) {
    const now = W.seasons.live().map((s) => s.id), live = now.includes(id);
    $$('[data-only]').forEach((el) => el.toggleAttribute('hidden', !el.dataset.only.split(/\s+/).includes(id) || (el.hasAttribute('data-in-season') && !live)));   // SVG elements have no .hidden property
    $$('[data-out-of-season]').forEach((el) => el.toggleAttribute('hidden', el.dataset.outOfSeason.split(/\s+/).some((s) => now.includes(s))));
  }

  /* ------------------------------------------------------------------ */
  {
    const id = W.seasons.active || W.seasons.current();
    applyOnly(id);
    if (footerEl) footerEl.innerHTML = footerArt(id);
  }
})();
